// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADO-D0AidWAdw6VaxzPikMv8QLit3Y9CI',
    appId: '1:959076229091:web:d6796bbac0727080030ad6',
    messagingSenderId: '959076229091',
    projectId: 'chatapp-e03d9',
    authDomain: 'chatapp-e03d9.firebaseapp.com',
    storageBucket: 'chatapp-e03d9.firebasestorage.app',
    measurementId: 'G-SD09BHK1R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHYBhWf5K6dQzZYTWlu7zOR6z0K90qc18',
    appId: '1:959076229091:android:47ba9541dec37dde030ad6',
    messagingSenderId: '959076229091',
    projectId: 'chatapp-e03d9',
    storageBucket: 'chatapp-e03d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCqnUK2OzsBev9O3iZRmtK3se1H18dFKw',
    appId: '1:959076229091:ios:38ba7991b4611e6f030ad6',
    messagingSenderId: '959076229091',
    projectId: 'chatapp-e03d9',
    storageBucket: 'chatapp-e03d9.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCqnUK2OzsBev9O3iZRmtK3se1H18dFKw',
    appId: '1:959076229091:ios:38ba7991b4611e6f030ad6',
    messagingSenderId: '959076229091',
    projectId: 'chatapp-e03d9',
    storageBucket: 'chatapp-e03d9.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADO-D0AidWAdw6VaxzPikMv8QLit3Y9CI',
    appId: '1:959076229091:web:d2280b63471d63ec030ad6',
    messagingSenderId: '959076229091',
    projectId: 'chatapp-e03d9',
    authDomain: 'chatapp-e03d9.firebaseapp.com',
    storageBucket: 'chatapp-e03d9.firebasestorage.app',
    measurementId: 'G-MNC9Q57MFD',
  );
}
